-- DRAGONLOST 011 (UTF-8). Run the whole file as a script, not one statement at a time.
-- DBeaver: Execute SQL Script (Alt+X). Single-statement run (Ctrl+Enter) on UPDATE causes errors.
-- Миграция: русские описания shop_items (перевод с официальных английских текстов Rust)
-- Запуск: mysql -u ... -p dragonlost_web < backend/database/migrations/011-shop-items-descriptions-ru.sql
-- После 010 или вместо неё — перезаписывает поле description.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `dragonlost_web`;

UPDATE `shop_items` SET `description` = 'Патроны для пистолета. На большой дистанции теряют скорость, урон немного ниже.' WHERE `rust_item_code` = 'ammo.pistol';
UPDATE `shop_items` SET `description` = 'Медленные патроны с огненным уроном. Небольшой шанс вызвать пожар.' WHERE `rust_item_code` = 'ammo.pistol.fire';
UPDATE `shop_items` SET `description` = 'Быстрые патроны: меньше падение траектории и чуть выше урон на дальних дистанциях.' WHERE `rust_item_code` = 'ammo.pistol.hv';
UPDATE `shop_items` SET `description` = 'Патроны для винтовки. На большой дистанции теряют скорость, урон немного ниже.' WHERE `rust_item_code` = 'ammo.rifle';
UPDATE `shop_items` SET `description` = 'Взрывается при попадании, нанося небольшой осколочный урон объектам рядом.' WHERE `rust_item_code` = 'ammo.rifle.explosive';
UPDATE `shop_items` SET `description` = 'Быстрые патроны: меньше падение траектории и чуть выше урон на дальних дистанциях.' WHERE `rust_item_code` = 'ammo.rifle.hv';
UPDATE `shop_items` SET `description` = 'Медленные патроны с огненным уроном. Небольшой шанс вызвать пожар.' WHERE `rust_item_code` = 'ammo.rifle.incendiary';
UPDATE `shop_items` SET `description` = 'Боеприпас для гранатомёта. Неуправляемая ракета ближней и средней дальности с сильным уроном по площади при попадании.' WHERE `rust_item_code` = 'ammo.rocket.basic';
UPDATE `shop_items` SET `description` = 'Патроны для дробовика.' WHERE `rust_item_code` = 'ammo.shotgun';
UPDATE `shop_items` SET `description` = 'Зажигательные патроны для дробовика.' WHERE `rust_item_code` = 'ammo.shotgun.fire';
UPDATE `shop_items` SET `description` = 'Крупная пуля для дробовика.' WHERE `rust_item_code` = 'ammo.shotgun.slug';
UPDATE `shop_items` SET `description` = 'Автоматическая электрическая турель поражает движущиеся цели в поле зрения. Нужно установить стрелковое оружие и подходящие патроны. Турель ищет цели в секторе 180 град. в сторону, куда вы смотрели при установке. Требуется 10 единиц электроэнергии.' WHERE `rust_item_code` = 'autoturret';
UPDATE `shop_items` SET `description` = 'Укрытие в перестрелках. Быстро разрушается вне зоны шкафа.' WHERE `rust_item_code` = 'barricade.wood.cover';
UPDATE `shop_items` SET `description` = 'Кровать: точка возрождения, перезарядка чаще, чем у спального мешка. Нужно ставить внутри постройки.' WHERE `rust_item_code` = 'bed';
UPDATE `shop_items` SET `description` = 'Чёрная малина с кустов. Слегка восстанавливает здоровье, голод и жажду.' WHERE `rust_item_code` = 'black.raspberries';
UPDATE `shop_items` SET `description` = 'Камера видеонаблюдения для охраны базы в реальном времени при питании и подключении к компьютерной станции.' WHERE `rust_item_code` = 'cctv.camera';
UPDATE `shop_items` SET `description` = 'Бензопила. Эффективна против деревьев и мягких целей. Работает на низкосортном топливе.' WHERE `rust_item_code` = 'chainsaw';
UPDATE `shop_items` SET `description` = 'Шлем из кофейной банки. Даёт защиту головы от урона.' WHERE `rust_item_code` = 'coffeecan.helmet';
UPDATE `shop_items` SET `description` = 'Компьютерная станция для удалённого управления (камеры и турели).' WHERE `rust_item_code` = 'computerstation';
UPDATE `shop_items` SET `description` = 'Топливо для карьера и гигантского экскаватора.' WHERE `rust_item_code` = 'diesel_barrel';
UPDATE `shop_items` SET `description` = 'Очень прочная двойная дверь с люком для обзора и стрельбы.' WHERE `rust_item_code` = 'door.double.hinged.toptier';
UPDATE `shop_items` SET `description` = 'Очень прочная дверь с люком для обзора и стрельбы.' WHERE `rust_item_code` = 'door.hinged.toptier';
UPDATE `shop_items` SET `description` = 'Большой аккумулятор. Минимум 5 секунд заряда перед разрядкой. Можно включать последовательно. Скорость зарядки зависит от входной мощности, КПД до 80%.' WHERE `rust_item_code` = 'electric.battery.rechargable.large';
UPDATE `shop_items` SET `description` = 'Средний аккумулятор. Минимум 5 секунд заряда перед разрядкой. Можно включать последовательно. Скорость зарядки зависит от входной мощности, КПД до 80%.' WHERE `rust_item_code` = 'electric.battery.rechargable.medium';
UPDATE `shop_items` SET `description` = 'Небольшой генератор на низкосортном топливе, выдаёт 40 единиц электроэнергии.' WHERE `rust_item_code` = 'electric.fuelgenerator.small';
UPDATE `shop_items` SET `description` = 'Электрическая печь: плавка за счёт электричества, без обычного топлива.' WHERE `rust_item_code` = 'electric.furnace';
UPDATE `shop_items` SET `description` = 'Солнечная панель: превращает свет в энергию. Выход зависит от силы света и угла к солнцу.' WHERE `rust_item_code` = 'electric.solarpanel.large';
UPDATE `shop_items` SET `description` = 'Небольшой заряд из гранат в банках. Подходит для уничтожения деревянных и металлических дверей.' WHERE `rust_item_code` = 'explosive.satchel';
UPDATE `shop_items` SET `description` = 'С4 для прорыва баз.' WHERE `rust_item_code` = 'explosive.timed';
UPDATE `shop_items` SET `description` = 'Огнемёт. Боеприпас — низкосортное топливо.' WHERE `rust_item_code` = 'flamethrower';
UPDATE `shop_items` SET `description` = 'Печь для переплавки больших объёмов руды. Сложно защитить, ставится на землю.' WHERE `rust_item_code` = 'furnace.large';
UPDATE `shop_items` SET `description` = 'Ненадёжный электрический предохранитель: на время пропускает ток.' WHERE `rust_item_code` = 'fuse';
UPDATE `shop_items` SET `description` = 'Набор шестерёнок: часть рабочая, часть нет.' WHERE `rust_item_code` = 'gears';
UPDATE `shop_items` SET `description` = 'Превращает энергию ветра в электричество. Выход зависит от скорости ветра; на большой высоте ветер сильнее.' WHERE `rust_item_code` = 'generator.wind.scrap';
UPDATE `shop_items` SET `description` = 'Надёжная армейская граната, бросок на небольшое расстояние. Смертельна вблизи при взрыве.' WHERE `rust_item_code` = 'grenade.f1';
UPDATE `shop_items` SET `description` = 'Защитный костюм из радиационностойкой резины.' WHERE `rust_item_code` = 'hazmatsuit';
UPDATE `shop_items` SET `description` = 'Чистый целебный чай: утоляет жажду и сильно лечит со временем.' WHERE `rust_item_code` = 'healingtea.pure';
UPDATE `shop_items` SET `description` = 'Пусковая установка ракет с наведением. После пуска цель нужно удерживать в прицеле до попадания. Отвлекается ловушками-ракетами.' WHERE `rust_item_code` = 'homingmissile.launcher';
UPDATE `shop_items` SET `description` = 'Толстовка.' WHERE `rust_item_code` = 'hoodie';
UPDATE `shop_items` SET `description` = 'Пневматический отбойный молоток для руды. Сила настолько велика, что прицеливаться в слабые места не нужно. Эффективен и по плоти. Заправляется у верстака.' WHERE `rust_item_code` = 'jackhammer';
UPDATE `shop_items` SET `description` = 'Ключ-карта среднего уровня доступа.' WHERE `rust_item_code` = 'keycard_blue';
UPDATE `shop_items` SET `description` = 'Карта низкого уровня — доступ в простые зоны.' WHERE `rust_item_code` = 'keycard_green';
UPDATE `shop_items` SET `description` = 'Карта высокого уровня — доступ в самые защищённые зоны.' WHERE `rust_item_code` = 'keycard_red';
UPDATE `shop_items` SET `description` = 'Лестница для подъёма по стенам в чужих базах.' WHERE `rust_item_code` = 'ladder.wooden.wall';
UPDATE `shop_items` SET `description` = 'Большая аптечка: постепенно доводит здоровье до максимума и сразу останавливает кровотечение. В панели быстрого доступа гарантирует 100% выход из раненого состояния.' WHERE `rust_item_code` = 'largemedkit';
UPDATE `shop_items` SET `description` = 'Пулемёт с высоким уроном и скорострельностью, ленточное питание.' WHERE `rust_item_code` = 'lmg.m249';
UPDATE `shop_items` SET `description` = 'Чистый чай здоровья: утоляет жажду и на время сильно повышает максимум здоровья.' WHERE `rust_item_code` = 'maxhealthtea.pure';
UPDATE `shop_items` SET `description` = 'Металлическая маска — отличная защита головы от любых атак.' WHERE `rust_item_code` = 'metal.facemask';
UPDATE `shop_items` SET `description` = 'Металлическая пластина на торс — сильная защита от любых атак.' WHERE `rust_item_code` = 'metal.plate.torso';
UPDATE `shop_items` SET `description` = 'Качественный металл для брони и оружия.' WHERE `rust_item_code` = 'metal.refined';
UPDATE `shop_items` SET `description` = 'Металлическое лезвие для создания холодного оружия.' WHERE `rust_item_code` = 'metalblade';
UPDATE `shop_items` SET `description` = 'Металлическая труба.' WHERE `rust_item_code` = 'metalpipe';
UPDATE `shop_items` SET `description` = 'Металлическая пружина: движение или сопротивление в механизмах.' WHERE `rust_item_code` = 'metalspring';
UPDATE `shop_items` SET `description` = 'Военный огнемёт. Боеприпас — низкосортное топливо.' WHERE `rust_item_code` = 'military_flamethrower';
UPDATE `shop_items` SET `description` = '40-мм шестиствольный полуавтоматический гранатомёт.' WHERE `rust_item_code` = 'multiplegrenadelauncher';
UPDATE `shop_items` SET `description` = 'Ночное зрение за счёт инфракрасной подсветки и усиления. Батареи заряжаются на верстаке 2 уровня. Не сочетается со шлемом.' WHERE `rust_item_code` = 'nightvisiongoggles';
UPDATE `shop_items` SET `description` = 'Чистый рудный чай: утоляет жажду и на время сильно повышает добычу руды.' WHERE `rust_item_code` = 'oretea.pure';
UPDATE `shop_items` SET `description` = 'Штаны — удобная и прочная нижняя часть брони, защита от урона и непогоды.' WHERE `rust_item_code` = 'pants';
UPDATE `shop_items` SET `description` = 'Полуавтоматический пистолет: высокая скорострельность и точность. Военное качество.' WHERE `rust_item_code` = 'pistol.m92';
UPDATE `shop_items` SET `description` = 'Прототип пистолета с очередью на 3 выстрела. Силён вблизи. Переключение одиночный/очередь: смена режима огня.' WHERE `rust_item_code` = 'pistol.prototype17';
UPDATE `shop_items` SET `description` = 'Мощный шестизарядный револьвер.' WHERE `rust_item_code` = 'pistol.python';
UPDATE `shop_items` SET `description` = 'Стандартный восьмизарядный револьвер.' WHERE `rust_item_code` = 'pistol.revolver';
UPDATE `shop_items` SET `description` = 'Полуавтоматический пистолет: быстрая и точная стрельба.' WHERE `rust_item_code` = 'pistol.semiauto';
UPDATE `shop_items` SET `description` = 'Чистый чай: утоляет жажду и на время сильно повышает сопротивление радиации.' WHERE `rust_item_code` = 'radiationresisttea.pure';
UPDATE `shop_items` SET `description` = 'Автомат с высоким уроном.' WHERE `rust_item_code` = 'rifle.ak';
UPDATE `shop_items` SET `description` = 'Мощная снайперская винтовка с высокой точностью и дальностью.' WHERE `rust_item_code` = 'rifle.bolt';
UPDATE `shop_items` SET `description` = 'Военная снайперская винтовка: высокая мощь, дальность и точность.' WHERE `rust_item_code` = 'rifle.l96';
UPDATE `shop_items` SET `description` = 'Лёгкая штурмовая винтовка высокой мощи.' WHERE `rust_item_code` = 'rifle.lr300';
UPDATE `shop_items` SET `description` = 'Военная самозарядная винтовка.' WHERE `rust_item_code` = 'rifle.m39';
UPDATE `shop_items` SET `description` = 'Самозарядная винтовка.' WHERE `rust_item_code` = 'rifle.semiauto';
UPDATE `shop_items` SET `description` = 'Перчатки из металла — хорошая защита для рук и верхней части тела.' WHERE `rust_item_code` = 'roadsign.gloves';
UPDATE `shop_items` SET `description` = 'Грубый нагрудник из дорожных знаков.' WHERE `rust_item_code` = 'roadsign.jacket';
UPDATE `shop_items` SET `description` = 'Грубая защита ног из дорожных знаков. Умеренная защита от ближнего боя и снарядов.' WHERE `rust_item_code` = 'roadsign.kilt';
UPDATE `shop_items` SET `description` = 'Куски металлических дорожных знаков.' WHERE `rust_item_code` = 'roadsigns';
UPDATE `shop_items` SET `description` = 'Искусное исполнение и разрушительная сила.' WHERE `rust_item_code` = 'rocket.launcher';
UPDATE `shop_items` SET `description` = 'Кусок верёвки.' WHERE `rust_item_code` = 'rope';
UPDATE `shop_items` SET `description` = 'Ударно-спусковой механизм полуавтоматического оружия.' WHERE `rust_item_code` = 'semibody';
UPDATE `shop_items` SET `description` = 'Швейный набор для продвинутой одежды.' WHERE `rust_item_code` = 'sewingkit';
UPDATE `shop_items` SET `description` = 'Листовой металл, обрезки.' WHERE `rust_item_code` = 'sheetmetal';
UPDATE `shop_items` SET `description` = 'Прочные рабочие ботинки: защита пальцев, холода и урона.' WHERE `rust_item_code` = 'shoes.boots';
UPDATE `shop_items` SET `description` = 'Двуствольный дробовик: два выстрела подряд без перезарядки.' WHERE `rust_item_code` = 'shotgun.double';
UPDATE `shop_items` SET `description` = 'Полуавтоматический армейский дробовик.' WHERE `rust_item_code` = 'shotgun.m4';
UPDATE `shop_items` SET `description` = 'Дробовик на 8 патронов.' WHERE `rust_item_code` = 'shotgun.pump';
UPDATE `shop_items` SET `description` = 'Полуавтоматический армейский дробовик.' WHERE `rust_item_code` = 'shotgun.spas12';
UPDATE `shop_items` SET `description` = 'Дробовик: один выстрел, затем перезарядка.' WHERE `rust_item_code` = 'shotgun.waterpipe';
UPDATE `shop_items` SET `description` = 'Небольшой НПЗ: перерабатывает сырую нефть в низкосортное топливо.' WHERE `rust_item_code` = 'small.oil.refinery';
UPDATE `shop_items` SET `description` = 'Скорострельный пулемёт: скорость важнее точности и дальности.' WHERE `rust_item_code` = 'smg.2';
UPDATE `shop_items` SET `description` = 'Пистолет-пулемёт среднего урона.' WHERE `rust_item_code` = 'smg.mp5';
UPDATE `shop_items` SET `description` = 'Пистолет-пулемёт среднего урона.' WHERE `rust_item_code` = 'smg.thompson';
UPDATE `shop_items` SET `description` = 'Механизм ПП для сборки оружия под пистолетные патроны с автоматическим огнём.' WHERE `rust_item_code` = 'smgbody';
UPDATE `shop_items` SET `description` = 'Подводное ружьё: стреляет только под водой. Удобно против акул.' WHERE `rust_item_code` = 'speargun';
UPDATE `shop_items` SET `description` = 'Фиолетовый дымовой сигнал. Отмечает место для сброса с воздуха.' WHERE `rust_item_code` = 'supply.signal';
UPDATE `shop_items` SET `description` = 'Лечит вас или союзника: ЛКМ — себя, ПКМ — цель.' WHERE `rust_item_code` = 'syringe.medical';
UPDATE `shop_items` SET `description` = 'Тактические перчатки: защита и стабилизация оружия, выше точность.' WHERE `rust_item_code` = 'tactical.gloves';
UPDATE `shop_items` SET `description` = 'Компьютер с ПО для анализа видео и вычисления поворотов объектов в кадре (наведение турелей).' WHERE `rust_item_code` = 'targeting.computer';
UPDATE `shop_items` SET `description` = 'Водонепроницаемый брезент.' WHERE `rust_item_code` = 'tarp';
UPDATE `shop_items` SET `description` = 'Набор случайных технических деталей.' WHERE `rust_item_code` = 'techparts';
UPDATE `shop_items` SET `description` = 'Подъёмные ворота в гаражную раму.' WHERE `rust_item_code` = 'wall.frame.garagedoor';
UPDATE `shop_items` SET `description` = 'Крупный военный прицел с переменной кратностью от 4x до 16x.' WHERE `rust_item_code` = 'weapon.mod.16x.scope';
UPDATE `shop_items` SET `description` = 'Крупный военный прицел с переменной кратностью от 4x до 16x.' WHERE `rust_item_code` = 'weapon.mod.8x.scope';
UPDATE `shop_items` SET `description` = 'Крепится на оружие. Луч света. F (по умолчанию) — вкл/выкл.' WHERE `rust_item_code` = 'weapon.mod.flashlight';
UPDATE `shop_items` SET `description` = 'Лазерная голографическая метка, указывает на цель независимо от угла обзора.' WHERE `rust_item_code` = 'weapon.mod.holosight';
UPDATE `shop_items` SET `description` = 'Крепится на оружие. Подсветка цели и меньше раскачка прицела.' WHERE `rust_item_code` = 'weapon.mod.lasersight';
UPDATE `shop_items` SET `description` = 'Повышает скорострельность за счёт отвода газов в механизм, ценой точности очереди.' WHERE `rust_item_code` = 'weapon.mod.muzzleboost';
UPDATE `shop_items` SET `description` = 'Снижает отдачу, но траектория может стать менее предсказуемой, урон по врагам чуть ниже.' WHERE `rust_item_code` = 'weapon.mod.muzzlebrake';
UPDATE `shop_items` SET `description` = 'Сильно глушит выстрел и убирает дульное пламя.' WHERE `rust_item_code` = 'weapon.mod.silencer';
UPDATE `shop_items` SET `description` = 'Чистый древесный чай: на время сильно повышает добычу дерева.' WHERE `rust_item_code` = 'woodtea.pure';
UPDATE `shop_items` SET `description` = 'Открывает крафт предметов, требующих верстак 1 уровня.' WHERE `rust_item_code` = 'workbench1';
UPDATE `shop_items` SET `description` = 'Открывает крафт предметов, требующих верстак 2 уровня.' WHERE `rust_item_code` = 'workbench2';
UPDATE `shop_items` SET `description` = 'Открывает крафт предметов, требующих верстак 3 уровня.' WHERE `rust_item_code` = 'workbench3';
